[Personal]
source        = imaps://xdavidwuph%40gmail.com@imap.gmail.com:993
source-cred-cmd = hiq -dFpassword host=gmail.com proto=email
outgoing      = smtp+plain://xdavidwuph%40gmail.com@smtp.gmail.com:587
outgoing-cred-cmd = hiq -dFpassword host=gmail.com proto=email
default       = INBOX
from          = Pinghao Wu <xdavidwuph@gmail.com>
copy-to       = Sent

[CSCC]
source		= imaps://wuph0612@imap.cs.nctu.edu.tw
source-cred-cmd	= hiq -dFpassword host=cs.nctu.edu.tw 
outgoing	= smtps://wuph0612@smtp.cs.nctu.edu.tw
outgoing-cred-cmd	= hiq -dFpassword host=cs.nctu.edu.tw 
default		= INBOX
from		= 吳秉澔 <wuph0612@it.cs.nycu.edu.tw>
copy-to		= Sent
signature-file	= ~/.config/aerc/cscc-signature
